# Generated by Django 5.2.16 on 2026-07-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise_type', models.CharField(choices=[('mc', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('translate', 'Translation'), ('match', 'Matching'), ('listen', 'Listening'), ('speak', 'Speaking'), ('read', 'Reading Comprehension'), ('order', 'Word Order')], max_length=10)),
                ('question', models.TextField()),
                ('question_ru', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='options, correct_answer, hints, audio_text')),
                ('points', models.PositiveSmallIntegerField(default=5)),
                ('skill', models.CharField(choices=[('alphabet', 'Alphabet & Phonetics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('dialogue', 'Dialogues')], default='vocabulary', max_length=20)),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LevelExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_score', models.FloatField(default=70.0)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30)),
                ('questions', models.JSONField(default=list, help_text='List of exam question objects')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(db_index=True, max_length=200)),
                ('russian', models.CharField(max_length=200)),
                ('transcription', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='A1', max_length=10)),
                ('example_sentence', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('audio_url', models.CharField(blank=True, max_length=500)),
                ('frequency_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['frequency_rank', 'english'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.learnerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], db_index=True, max_length=10)),
                ('sub_level', models.CharField(blank=True, help_text='e.g. A1.1', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet & Phonetics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('dialogue', 'Dialogues')], max_length=20)),
                ('content', models.JSONField(default=dict, help_text='Structured lesson blocks')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=15)),
                ('xp_reward', models.PositiveSmallIntegerField(default=20)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lesson'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='users.learnerprofile')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.levelexam')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_spent', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveSmallIntegerField(default=0)),
                ('exercises_done', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.learnerprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('review', 'Needs Review')], default='not_started', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='users.learnerprofile')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='SRSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=500)),
                ('back', models.CharField(max_length=500)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('last_review', models.DateField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_items', to='users.learnerprofile')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.word')),
            ],
            options={
                'unique_together': {('user', 'front')},
            },
        ),
    ]
