# Generated by Django 5.2.16 on 2026-07-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('gutenberg', 'Project Gutenberg'), ('voa', 'VOA Learning English'), ('manual', 'Manual'), ('graded', 'Graded Reader')], default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], db_index=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cover_emoji', models.CharField(default='📖', max_length=10)),
                ('chapters', models.JSONField(default=list, help_text='[{title, text, word_count}]')),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_texts', to='learning.lesson')),
            ],
            options={
                'ordering': ['level', 'title'],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
