# Generated by Django 5.2.16 on 2026-07-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_readingtext'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='A1', max_length=10)),
                ('emoji', models.CharField(default='💬', max_length=10)),
                ('setting', models.CharField(blank=True, help_text='e.g. At a cafe', max_length=200)),
                ('turns', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PhrasePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pack_type', models.CharField(choices=[('shadow', 'Shadowing'), ('survival', 'Survival Phrases'), ('phonetics', 'Phonetics'), ('smalltalk', 'Small Talk')], max_length=20)),
                ('level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='A1', max_length=10)),
                ('emoji', models.CharField(default='🎤', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShadowPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('english', models.CharField(max_length=500)),
                ('russian', models.CharField(blank=True, max_length=500)),
                ('phonetic', models.CharField(blank=True, max_length=200)),
                ('tip', models.TextField(blank=True, help_text='Pronunciation tip for RU speakers')),
                ('slow_first', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='learning.phrasepack')),
            ],
            options={
                'ordering': ['pack', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.CharField(max_length=500)),
                ('spoken', models.CharField(blank=True, max_length=500)),
                ('score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to='users.learnerprofile')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.shadowphrase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('best_score', models.FloatField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='users.learnerprofile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.dialoguescenario')),
            ],
            options={
                'unique_together': {('user', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='SpeakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('phrases_practiced', models.PositiveSmallIntegerField(default=0)),
                ('dialogues_done', models.PositiveSmallIntegerField(default=0)),
                ('avg_pronunciation', models.FloatField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speak_sessions', to='users.learnerprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
