# Generated by Django 5.2.16 on 2026-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_dialoguescenario_phrasepack_shadowphrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('translate', 'Translation'), ('match', 'Matching'), ('listen', 'Listening'), ('speak', 'Speaking'), ('read', 'Reading Comprehension'), ('order', 'Word Order'), ('write', 'Guided Writing')], max_length=10),
        ),
    ]
