# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_alter_exercise_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingtext",
            name="source",
            field=models.CharField(
                choices=[
                    ("gutenberg", "Project Gutenberg"),
                    ("voa", "VOA Learning English"),
                    ("manual", "Manual"),
                    ("graded", "Graded Reader"),
                    ("english_journey_original", "English Journey Original"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
