# Generated by Django 5.2.16 on 2026-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('language_code', models.CharField(default='ru', max_length=10)),
                ('current_level', models.CharField(choices=[('PRE_A1', 'Pre-A1 (Alphabet)'), ('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='PRE_A1', max_length=10)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('daily_goal_minutes', models.PositiveSmallIntegerField(default=20)),
                ('minutes_today', models.PositiveSmallIntegerField(default=0)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('skill_listening', models.FloatField(default=0)),
                ('skill_reading', models.FloatField(default=0)),
                ('skill_writing', models.FloatField(default=0)),
                ('skill_speaking', models.FloatField(default=0)),
                ('skill_grammar', models.FloatField(default=0)),
                ('skill_vocabulary', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
            },
        ),
    ]
